image: node:16.8.0

pipelines:
  branches:
    development:
      - step:
          name: build
          script:
            - yarn install && yarn build:staging
          artifacts:
            - build/**
      - step:
          name: Deploy to Firebase
          deployment: staging
          script:
            - pipe: atlassian/firebase-deploy:1.3.0
              variables:
                FIREBASE_TOKEN: $FIREBASE_TOKEN
                EXTRA_ARGS: '--only hosting'
                MULTI_SITES_CONFIG: >
                  [{
                    "TARGET": "staging",
                    "RESOURCE": "wardrobe-uwear-stg"
                  }]
    master:
      - step:
          name: build
          script:
            - yarn install && yarn build
          artifacts:
            - build/**
      - step:
          name: Deploy to Firebase
          deployment: production
          script:
            - pipe: atlassian/firebase-deploy:1.3.0
              variables:
                FIREBASE_TOKEN: $FIREBASE_TOKEN
                EXTRA_ARGS: '--only hosting'
                MULTI_SITES_CONFIG: >
                  [{
                    "TARGET": "production",
                    "RESOURCE": "wardrobe-uwear"
                  }]