image: node:16.8.0

pipelines:
  branches:
    development:
      - step:
          name: Build
          script:
            - yarn install && yarn build:staging
          artifacts:
            - build/**
      - step:
          name: Deploy to Firebase
          deployment: staging
          script:
            - pipe: atlassian/firebase-deploy:1.3.0
              variables:
                FIREBASE_TOKEN: $FIREBASE_TOKEN
                PROJECT_ID: 'wwardrobe-stg-uwear'
                DEBUG: 'true'
    master:
      - step:
          name: Build
          script:
            - yarn install && yarn build
          artifacts:
            - build/**
      - step:
          name: Deploy to Firebase
          deployment: production
          script:
            - pipe: atlassian/firebase-deploy:1.3.0
              variables:
                FIREBASE_TOKEN: $FIREBASE_TOKEN
                PROJECT_ID: 'wardrobe-uwear'
                DEBUG: 'true'