image: node:16.10.0

pipelines:
  branches:
    development:
      - step:
          name: Build
          script:
            - yarn install
            - REACT_APP_FIREBASE_API_KEY=$REACT_APP_STAGING_FIREBASE_API_KEY yarn build:staging
            - REACT_APP_SENTRY_ORG=$REACT_APP_SENTRY_ORG REACT_APP_SENTRY_PROJECT=$REACT_APP_SENTRY_PROJECT REACT_APP_SENTRY_AUTH_TOKEN=$REACT_APP_SENTRY_AUTH_TOKEN yarn upload-sourcemaps
            - find ./build -name *.map -delete
          artifacts:
            - build/**
      - step:
          name: Deploy to Firebase
          deployment: staging
          script:
            - pipe: atlassian/firebase-deploy:3.0.0
              variables:
                FIREBASE_TOKEN: $FIREBASE_TOKEN
                PROJECT_ID: "staging"
                DEBUG: "true"
    master:
      - step:
          name: Build
          script:
            - yarn install
            - REACT_APP_FIREBASE_API_KEY=$REACT_APP_FIREBASE_API_KEY yarn build
            - REACT_APP_SENTRY_ORG=$REACT_APP_SENTRY_ORG REACT_APP_SENTRY_PROJECT=$REACT_APP_SENTRY_PROJECT REACT_APP_SENTRY_AUTH_TOKEN=$REACT_APP_SENTRY_AUTH_TOKEN yarn upload-sourcemaps
            - find ./build -name *.map -delete
          artifacts:
            - build/**
      - step:
          name: Deploy to Firebase
          deployment: production
          script:
            - pipe: atlassian/firebase-deploy:3.0.0
              variables:
                FIREBASE_TOKEN: $FIREBASE_TOKEN
                PROJECT_ID: "production"
                DEBUG: "true"
